### PR TITLE
Bug Fixes, Improvements, and Features

### LINKED ISSUE #296: colon in URL
My markdown files have often links containing colon. Such markdown files fail to render with MarkdownPreview.

Example valid link:
https://courses.edx.org/courses/course-v1:BerkeleyX+GG101x+3T2015/courseware/87a692d1ab3e4e3bb0cf3d7de904c156/5b56cf2834ba4476b7e1bc8b6257280c/
(notice there is colon before BerkeleyX)

As you can see from traceback proveded below, the colon is replaced by | and some error message is reported about bad URL and rendering fails. Could this be fixed? Thanks.

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 550, in run_
    return self.run(edit, **args)
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 1126, in run
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 759, in run
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 708, in convert_markdown
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 553, in postprocessor_pathconverter
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 553, in <lambda>
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 541, in repl
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 541, in <lambda>
  File "MarkdownPreview in C:\Users\smi\AppData\Roaming\Sublime Text 3\Installed Packages\Markdown Preview.sublime-package", line 281, in repl_absolute
  File "./nturl2path.py", line 26, in url2pathname
OSError: Bad URL: /courses/course-v1|BerkeleyX+GG101x+3T2015/courseware/89757399587a49b7bf91b3c907744270/dd810b686ac44f01a7ac1251ffe50ff9/

### PR DESCRIPTION
**Pull request by facelessuser**
### Fixes

- Fix #296 (absolute url handling bug)

### Improvements

- Improve some documentation.
- Remove internal Pygments and PyYaml.  Instead use Package Control dependencies to get PyYaml and Pygments (in the future maybe this can be done for Python Markdown as well).  This means no more messy hand merged upgrades.
- Release documents updated with the assumption to be released as 1.3.0.

### Features

- Generic external markdown parser support.  Things like MultiMarkdown are now generically handled.  This should allow for people to include things like CommonMark or others.

### CODE REVIEW

**Comment by facelessuser** [comment]
Looks like we need to wait until Markdown 2.6.5 gets released as there is a rather annoying bug in 2.6.4 affecting inline code blocks inside tables.

**Comment by facelessuser** [comment]
Markdown 2.6.5 was released which fixes the critical bug.  It has been merged in.

**Comment by revolunet** [comment]
thanks @facelessuser, this is huge ! can this be merged ?

**Comment by facelessuser** [comment]
I believe it can be merged as it is based off the most recent tip.

I was more waiting to see if you were okay with the direction I decided.  Keeping up Pygments and such as internal dependencies was a pain as we had to hand merge them all (well mainly Pygments), so I decided to use external dependencies.  I also realized that not everyone would understand how to hand merge Pygments, so I felt the sooner I could drop it the better.  I removed all but `markdown` as the official `markdown` library doesn't support Python 2.6, so we are still vendoring it at the present to support ST2 and ST3.

The generalized external markdown parser support technically breaks backwords compatibility with old multimarkdown support, but I am okay with that as the new method supports multimarkdown, commonmark, etc.

I often think in retrospect that I should break this up into separate pulls...but I just get rolling, and then I have all these changes.  Oh well :smile:.

**Comment by revolunet** [comment]
totally agree for external dependencies, good move !

**Comment by facelessuser** [comment]
If you are okay, then I will merge soon.  I may do a little more ST2 regression testing first, but then I will go ahead and merge.

**Comment by revolunet** [comment]
Looks great to me :)

**Pull request merged**
