### PR TITLE
Update markdown.css to match closer to Github's

### PR DESCRIPTION
**Pull request by publicarray**
I prefer the content to be a bit wider than just 45em (~720px) so this pull request fixes that.

### CODE REVIEW

**Comment by revolunet** [comment]
indeed, 45em is too small

**Comment by revolunet** [comment]
lgtm

**Comment by jonathanfishner** [comment]
why it's not merged :/ ?

**Comment by publicarray** [comment]
@jonathanfishner I asked myself that question about a year ago. 😆

**Comment by revolunet** [comment]
and....it's......mer....ged !

**Comment by revolunet** [comment]
apologies for the delay !

**Comment by publicarray** [comment]
Thanks 🎉 and no worries.

**Pull request merged**
